title: BMCircuits
description: Electronic consulting — PCB & hardware design, embedded systems, firmware development, Product test and CAD enclosure design.
url: "https://bmcircuits.com" # Github Pages = "https://bmcircuits.github.io"
baseurl: "" # Github Pages = "/bmcircuits"

author:
  name: Bobby McGlone
  email: info@bmcircuits.com
  location: Sydney, Australia

# Build settings
markdown: kramdown
permalink: /:categories/:title/
highlighter: rouge

# Collections
collections:
  portfolio:
    output: true
    permalink: /portfolio/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "portfolio"
    values:
      layout: "project"

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
  - wrangler.jsonc

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap